# Generated by Django 5.0.6 on 2026-08-14 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TryOnResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_image', models.ImageField(upload_to='tryon_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_results', to='recommendations.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Try-On Result',
                'verbose_name_plural': 'Try-On Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTryOnPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='tryon_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_photo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Try-On Photo',
                'verbose_name_plural': 'User Try-On Photos',
            },
        ),
    ]
