# Generated by Django 5.0.6 on 2026-08-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_tryon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertryonphoto',
            name='processed_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tryon_processed/'),
        ),
    ]
