# Generated by Django 5.0.6 on 2026-07-11 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_city', models.CharField(max_length=120)),
                ('destination_country', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trip_purpose', models.CharField(choices=[('leisure', 'Leisure'), ('business', 'Business'), ('adventure', 'Adventure'), ('beach', 'Beach'), ('city_break', 'City Break'), ('winter_sports', 'Winter Sports')], default='leisure', max_length=20)),
                ('avg_temperature_c', models.FloatField(blank=True, null=True)),
                ('min_temperature_c', models.FloatField(blank=True, null=True)),
                ('max_temperature_c', models.FloatField(blank=True, null=True)),
                ('weather_condition', models.CharField(blank=True, max_length=60)),
                ('weather_summary', models.TextField(blank=True)),
                ('packing_list', models.JSONField(blank=True, default=list)),
                ('outfit_suggestions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
