# Generated by Django 5.0.6 on 2026-07-21 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clothing_uploads/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClothingDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Shirt', 'Shirt'), ('T-Shirt', 'T-Shirt'), ('Hoodie', 'Hoodie'), ('Jacket', 'Jacket'), ('Blazer', 'Blazer'), ('Sweater', 'Sweater'), ('Jeans', 'Jeans'), ('Pants', 'Pants'), ('Shorts', 'Shorts'), ('Skirt', 'Skirt'), ('Dress', 'Dress'), ('Shoes', 'Shoes'), ('Sneakers', 'Sneakers'), ('Sandals', 'Sandals'), ('Cap', 'Cap'), ('Hat', 'Hat'), ('Belt', 'Belt'), ('Bag', 'Bag')], max_length=30)),
                ('confidence', models.FloatField(help_text='Detection confidence score between 0.0 and 1.0')),
                ('bbox_x1', models.FloatField(help_text='Top-left X coordinate')),
                ('bbox_y1', models.FloatField(help_text='Top-left Y coordinate')),
                ('bbox_x2', models.FloatField(help_text='Bottom-right X coordinate')),
                ('bbox_y2', models.FloatField(help_text='Bottom-right Y coordinate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='clothing_detection.clothingimage')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
        migrations.AddIndex(
            model_name='clothingimage',
            index=models.Index(fields=['user', '-created_at'], name='clothing_de_user_id_7b75a2_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingdetection',
            index=models.Index(fields=['image', 'category'], name='clothing_de_image_i_b24d8a_idx'),
        ),
    ]
