# Generated by Django 5.0.6 on 2026-07-11 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('business', 'Business'), ('party', 'Party'), ('sports', 'Sports'), ('travel', 'Travel'), ('beach', 'Beach'), ('wedding', 'Wedding'), ('loungewear', 'Loungewear')], default='casual', max_length=20)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('autumn', 'Autumn'), ('all_season', 'All Season'), ('rainy', 'Rainy')], default='all_season', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual Request'), ('weather', 'Weather-Based (Travel Planner)'), ('occasion', 'Occasion-Based')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Human-readable explanation of why this outfit was suggested.')),
                ('is_saved', models.BooleanField(default=False, help_text='Whether user explicitly saved this to history/favorites')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='recommendations', to='wardrobe.wardrobeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
