# Generated by Django 5.0.6 on 2026-07-11 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('dress', 'Dress'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear'), ('accessory', 'Accessory'), ('headwear', 'Headwear'), ('bag', 'Bag'), ('innerwear', 'Innerwear'), ('sportswear', 'Sportswear')], max_length=20)),
                ('color', models.CharField(max_length=40)),
                ('secondary_color', models.CharField(blank=True, max_length=40)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('autumn', 'Autumn'), ('all_season', 'All Season'), ('rainy', 'Rainy')], default='all_season', max_length=20)),
                ('occasion', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('business', 'Business'), ('party', 'Party'), ('sports', 'Sports'), ('travel', 'Travel'), ('beach', 'Beach'), ('wedding', 'Wedding'), ('loungewear', 'Loungewear')], default='casual', max_length=20)),
                ('material', models.CharField(blank=True, max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wardrobe/')),
                ('notes', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('is_favorite', models.BooleanField(default=False)),
                ('times_worn', models.PositiveIntegerField(default=0)),
                ('last_worn_at', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('occasion', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('business', 'Business'), ('party', 'Party'), ('sports', 'Sports'), ('travel', 'Travel'), ('beach', 'Beach'), ('wedding', 'Wedding'), ('loungewear', 'Loungewear')], default='casual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(related_name='outfits', to='wardrobe.wardrobeitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wardrobeitem',
            index=models.Index(fields=['user', 'category'], name='wardrobe_wa_user_id_0741de_idx'),
        ),
        migrations.AddIndex(
            model_name='wardrobeitem',
            index=models.Index(fields=['user', 'season'], name='wardrobe_wa_user_id_e1d068_idx'),
        ),
    ]
