# Generated by Django 5.0.6 on 2026-08-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='original_image',
            field=models.ImageField(blank=True, help_text='Raw uploaded image reference', null=True, upload_to='wardrobe/originals/'),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Clean garment-only image', null=True, upload_to='wardrobe/'),
        ),
    ]
