# Generated by Django 5.0.6 on 2026-08-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_wardrobeitem_original_image_alter_wardrobeitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='garment_3d_template',
            field=models.CharField(blank=True, default='', help_text='3D template category (tshirt, shirt, hoodie, jacket, jeans, pants, shorts, skirt, dress)', max_length=40),
        ),
    ]
