# Generated by Django 5.0.6 on 2026-08-18 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_wardrobeitem_garment_3d_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='garment_3d_template',
        ),
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='original_image',
        ),
    ]
